add try and except to get channels
danielperna84/ha-philipsjs pull request #14
Opened 2020-06-02 09:25 UTC by Rikbruggink

Hi!

My Philips tv doesn't hold any channels because we use it a glorified monitor. This patch adds a try and except to the getchannels function to allow for it to generate a exception and return a empty channels db.

2020-06-02 09:26 UTC, Rikbruggink commented
Oh and i bumped the version to 0.0.9 with this patch

2020-06-02 10:39 UTC, elupus commented
You can't have that a generic except. Please check the data instead for what the data is on this specific case. It doesn't warrent exception handling since it seem a valid use case.

2020-06-02 10:42 UTC, Rikbruggink commented
The reason i added the try and except is the net tv doesn't respond at al and generates a time-out on this call. With this patch it just sets the channels.list empty in that case

2020-06-02 10:45 UTC, elupus commented
Right, if that is the case you need to catch the timeout exception.

2020-06-02 10:46 UTC, Rikbruggink commented
So you would like to see the patch to only except on the timeout error instead of the generic one?

2020-06-02 10:49 UTC, elupus commented
Yes if that is the only way to detect the situation.

2020-06-02 11:58 UTC, Rikbruggink commented
changed the code to only return none on timeout errors

2020-06-02 13:13 UTC, elupus requested changes
No this won't work. Now you hide timeout exception for all retreivals. You are only allowed to handle the specific case we care about here.

2020-06-02 19:32 UTC, Rikbruggink commented
I know it is more general this way, but is not possible drill more down on this error from the request side of this because of the try except in the top. The only way we can filter more in the function is to do a try except with except (ConnectionFailure): in the function because of the top loop

2020-06-02 19:42 UTC, elupus commented
I don't understand what you are saying. Any uncaught exception is propagated up the caöl stack. So you can catch the timeout exception just in the channel list retrieval function.

2020-06-02 20:22 UTC, Rikbruggink commented
this works https://gist.github.com/Rikbruggink/70578d396687127d3aa8c6fbd1651bc4#file-__init__-py-L127

But the request timeout errors are not exposed in the function or i am not calling them correctly.

2020-06-02 20:41 UTC, elupus commented
It could be that requests.exceptions.Timeout inherits from RequestExcepton. So it will be caught there already and wrapped in the custom ConnectionException.

So if you need to catch the connection exception further out instead.

2021-07-05 07:43 UTC, gieljnssns commented
Any updates on this?
I'm also having troubles with the getChannel

```
Logger: homeassistant.components.philips_js
Source: components/philips_js/__init__.py:179
Integration: Philips TV (documentation, issues)
First occurred: 9:31:19 (1 occurrences)
Last logged: 9:31:19

Unexpected error fetching philips_js data:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 61, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 277, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 230, in handle_async_request
    response = await connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 115, in handle_async_request
    return await self.connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 69, in handle_async_request
    ) = await self._receive_response(timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 130, in _receive_response
    event = await self._receive_event(timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 166, in _receive_event
    data = await self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/asyncio.py", line 156, in read
    raise
  File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/haphilipsjs/__init__.py", line 493, in getReq
    resp = await self.session.get(self._url(path))
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1662, in get
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1426, in request
    response = await self.send(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1511, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1546, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1580, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1621, in _send_single_request
    ) = await transport.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 272, in handle_async_request
    (
  File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/philips_js/__init__.py", line 179, in _async_update_data
    await self.api.update()
  File "/usr/local/lib/python3.9/site-packages/haphilipsjs/__init__.py", line 639, in update
    await self.getChannels()
  File "/usr/local/lib/python3.9/site-packages/haphilipsjs/__init__.py", line 699, in getChannels
    r = cast(Optional[ChannelsType], await self.getReq("channels"))
  File "/usr/local/lib/python3.9/site-packages/haphilipsjs/__init__.py", line 506, in getReq
    raise GeneralFailure(err) from err
haphilipsjs.GeneralFailure
```

2021-07-05 09:31 UTC, elupus commented
> Any updates on this?
> I'm also having troubles with the getChannel
> 
> ```
> Logger: homeassistant.components.philips_js
> Source: components/philips_js/__init__.py:179
> Integration: Philips TV (documentation, issues)
> First occurred: 9:31:19 (1 occurrences)
> Last logged: 9:31:19
> 
> Unexpected error fetching philips_js data:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 61, in map_httpcore_exceptions
>     yield
>   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 277, in handle_async_request
>     ) = await self._pool.handle_async_request(
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 230, in handle_async_request
>     response = await connection.handle_async_request(
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 115, in handle_async_request
>     return await self.connection.handle_async_request(
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 69, in handle_async_request
>     ) = await self._receive_response(timeout)
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 130, in _receive_response
>     event = await self._receive_event(timeout)
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 166, in _receive_event
>     data = await self.socket.read(self.READ_NUM_BYTES, timeout)
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/asyncio.py", line 156, in read
>     raise
>   File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
>     raise to_exc(exc) from None
> httpcore.ReadTimeout
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/haphilipsjs/__init__.py", line 493, in getReq
>     resp = await self.session.get(self._url(path))
>   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1662, in get
>     return await self.request(
>   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1426, in request
>     response = await self.send(
>   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1511, in send
>     response = await self._send_handling_auth(
>   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1546, in _send_handling_auth
>     response = await self._send_handling_redirects(
>   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1580, in _send_handling_redirects
>     response = await self._send_single_request(request, timeout)
>   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1621, in _send_single_request
>     ) = await transport.handle_async_request(
>   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 272, in handle_async_request
>     (
>   File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 78, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> httpx.ReadTimeout
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
>     self.data = await self._async_update_data()
>   File "/usr/src/homeassistant/homeassistant/components/philips_js/__init__.py", line 179, in _async_update_data
>     await self.api.update()
>   File "/usr/local/lib/python3.9/site-packages/haphilipsjs/__init__.py", line 639, in update
>     await self.getChannels()
>   File "/usr/local/lib/python3.9/site-packages/haphilipsjs/__init__.py", line 699, in getChannels
>     r = cast(Optional[ChannelsType], await self.getReq("channels"))
>   File "/usr/local/lib/python3.9/site-packages/haphilipsjs/__init__.py", line 506, in getReq
>     raise GeneralFailure(err) from err
> haphilipsjs.GeneralFailure
> ```

I dont think your issue is the same. If you have at least one tuner tv channel it's likely a crashed tv. If you in plug and replug your tv, it will likely work for a while. It has crashed internally.

If you don't have any channels, just add one.

2021-07-05 09:38 UTC, gieljnssns commented
I have a lot of channels but they are locked. 
I only use this tv on hdmi with a settopbox from Telenet.

2021-07-05 10:30 UTC, elupus commented
Then just completely reboot your tv. Physical unplug.

2021-07-26 08:07 UTC, Rikbruggink commented
@gieljnssns This a PR not an issue tracker. Next time please open an issue instead and link to this PR there so we dont polute this thread much with talking about maybe other issues not related to this PR.

That being said, i do think we should try again on merging our work. I am still running on my own fork and maybe some others also. I will rebase the change and spend some time cleaning it up, so we can merge it.

2021-11-19 19:56 UTC, elupus commented
We should instead allow skipping channels retrieval completely.

2021-11-19 19:56 UTC, closed without merging